language: node_js
node_js:
- 12
script:
- ssh-keyscan -H 79.137.175.11 >> ~/.ssh/known_hosts
- chmod 600 ~/5factorial_id_rsa.pem
- npm run build
- mkdir ./deploy
- cp ./src/*.* ./deploy
- mv ./src/{css,dist,img,fonts} ./deploy
- scp -i ~/5factorial_id_rsa.pem -r ./deploy/* ubuntu@95.163.180.8:/home/ubuntu/5factorial
branches:
  only:
    - master
    - dev
    - issues
before_install:
- openssl aes-256-cbc -K $encrypted_173836cec267_key -iv $encrypted_173836cec267_iv
  -in 5factorial_id_rsa.pem.enc -out ~/5factorial_id_rsa.pem -d 